#!/usr/bin/env python3
import sys
import os
import colorsys
import argparse
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is not installed. Install with 'pacman -S python-pillow'")
    sys.exit(1)

def get_vibrant_color(img_path):
    img = Image.open(img_path).convert('RGB')
    # Resize for fast processing
    img.thumbnail((200, 200))
    # Quantize to 16 colors using fast octree
    quantized = img.quantize(colors=16, method=Image.Quantize.FASTOCTREE).convert('RGB')
    colors = quantized.getcolors(40000)
    
    # Fallback default: Intelligent Darkness Steel Blue
    best_color = (74, 109, 140) 
    max_vibrancy = -1
    
    for count, color in colors:
        r, g, b = color
        h, l, s = colorsys.rgb_to_hls(r/255.0, g/255.0, b/255.0)
        
        # Vibrancy score: prioritize high saturation, penalize extremes in lightness
        # We want accents that pop against dark backgrounds (lightness 0.3 - 0.7)
        if 0.2 < l < 0.8:
            score = s * count 
            if score > max_vibrancy:
                max_vibrancy = score
                best_color = color
                
    return best_color

def rgb_to_hex(r, g, b):
    return f"#{r:02x}{g:02x}{b:02x}"

def generate_theme_files(accent_rgb):
    r, g, b = accent_rgb
    h, l, s = colorsys.rgb_to_hls(r/255.0, g/255.0, b/255.0)
    
    # Accent Main
    accent = rgb_to_hex(r, g, b)
    
    # Accent Lighter (for highlights/hover)
    lr, lg, lb = colorsys.hls_to_rgb(h, min(1.0, l + 0.15), s)
    accent_light = rgb_to_hex(int(lr*255), int(lg*255), int(lb*255))
    
    # Accent Darker (for borders/inactive states)
    dr, dg, db = colorsys.hls_to_rgb(h, max(0.0, l - 0.2), s)
    accent_dark = rgb_to_hex(int(dr*255), int(dg*255), int(db*255))
    
    # Intelligent Darkness base colors (Static)
    bg_base = "#050505"
    bg_surface = "#0A0A0A"
    text_primary = "#C7CACD"
    
    theme_dir = Path.home() / ".config" / "icarus" / "theme"
    theme_dir.mkdir(parents=True, exist_ok=True)
    
    # 1. Hyprland colors.conf
    hypr_conf = f"""# Auto-generated by Icarus Palette
$bgBase = rgb(050505)
$bgSurface = rgb(0A0A0A)
$textPrimary = rgb(C7CACD)
$accent = rgb({accent[1:]})
$accentLight = rgb({accent_light[1:]})
$accentDark = rgb({accent_dark[1:]})
"""
    with open(theme_dir / "colors.conf", "w") as f:
        f.write(hypr_conf)
        
    # 2. CSS variables (Waybar, Wlogout)
    css_conf = f"""/* Auto-generated by Icarus Palette */
@define-color bgBase {bg_base};
@define-color bgSurface {bg_surface};
@define-color textPrimary {text_primary};
@define-color accent {accent};
@define-color accentLight {accent_light};
@define-color accentDark {accent_dark};
"""
    with open(theme_dir / "colors.css", "w") as f:
        f.write(css_conf)
        
    # 3. Shell variables (for bash scripts)
    sh_conf = f"""# Auto-generated by Icarus Palette
export ICARUS_BG_BASE="{bg_base}"
export ICARUS_BG_SURFACE="{bg_surface}"
export ICARUS_TEXT="{text_primary}"
export ICARUS_ACCENT="{accent}"
export ICARUS_ACCENT_LIGHT="{accent_light}"
export ICARUS_ACCENT_DARK="{accent_dark}"
"""
    with open(theme_dir / "colors.sh", "w") as f:
        f.write(sh_conf)
        
    # 4. Rofi colors.rasi
    rofi_conf = f"""/* Auto-generated by Icarus Palette */
* {{
    bg-base: {bg_base};
    bg-surface: {bg_surface};
    text-primary: {text_primary};
    accent: {accent};
    accent-light: {accent_light};
    accent-dark: {accent_dark};
}}
"""
    with open(theme_dir / "colors.rasi", "w") as f:
        f.write(rofi_conf)

    # 5. GTK CSS override
    gtk_conf = f"""/* Auto-generated by Icarus Palette */
@define-color accent_color {accent};
@define-color accent_bg_color {accent};
@define-color accent_fg_color {text_primary};
"""
    with open(theme_dir / "gtk.css", "w") as f:
        f.write(gtk_conf)
        
    # 6. Eww colors.scss
    scss_conf = f"""/* Auto-generated by Icarus Palette */
$bgBase: {bg_base};
$bgSurface: {bg_surface};
$textPrimary: {text_primary};
$accent: {accent};
$accentLight: {accent_light};
$accentDark: {accent_dark};
"""
    with open(theme_dir / "colors.scss", "w") as f:
        f.write(scss_conf)

    # 7. Update Cava config if it exists
    cava_config = Path.home() / ".config" / "cava" / "config"
    if cava_config.exists():
        update_cava(cava_config, accent, accent_light)
        # Soft reload cava
        os.system("killall -SIGUSR1 cava 2>/dev/null")

def update_cava(cava_path, c1, c2):
    with open(cava_path, 'r') as f:
        lines = f.readlines()
        
    for i, line in enumerate(lines):
        if line.startswith("gradient_color_1"):
            lines[i] = f"gradient_color_1 = {c1}\n"
        elif line.startswith("gradient_color_2"):
            lines[i] = f"gradient_color_2 = {c1}\n"
        elif line.startswith("gradient_color_3"):
            lines[i] = f"gradient_color_3 = {c2}\n"
        elif line.startswith("gradient_color_4"):
            lines[i] = f"gradient_color_4 = {c2}\n"
            
    with open(cava_path, 'w') as f:
        f.writelines(lines)

def main():
    parser = argparse.ArgumentParser(description="Icarus Dynamic Palette Generator")
    parser.add_argument("image", help="Path to the wallpaper image")
    args = parser.parse_args()
    
    if not os.path.exists(args.image):
        print(f"Error: {args.image} not found.")
        sys.exit(1)
        
    print(f"Extracting vibrant colors from {args.image}...")
    accent_rgb = get_vibrant_color(args.image)
    generate_theme_files(accent_rgb)
    
    print("Icarus palette updated successfully.")
    
    # Reload hyprland and waybar silently if running
    os.system("hyprctl reload >/dev/null 2>&1")
    os.system("killall -SIGUSR2 waybar >/dev/null 2>&1")

if __name__ == "__main__":
    main()
