# Open image files with image viewer (imv or swayimg if installed, fallback kitty +kitten icat)
protocol file
mime image/*
action launch --type=overlay kitty +kitten icat --hold ${FILE_PATH}

# Open text files with neovim (or nano)
protocol file
mime text/*
action launch --type=overlay nvim ${FILE_PATH}

# Open directories in terminal
protocol file
mime inode/directory
action launch --type=os-window --cwd ${FILE_PATH}
